version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ipoc-fileupl-urlcreator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12adap0wjbfyr"
s3_prefix = "ipoc-fileupl-urlcreator"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
